[package]
name = "esteria-api-client"
version = "0.0.1"
edition = "2024"

[lib]
name = "esteria_api_client"
crate-type = ["cdylib"]  # Important: needed for Python FFI

[dependencies]
futures = "0.3.31"
mimalloc = { version = "0.1.48", features = ["extended"] }
pyo3 = { version = "0.27.1", features = ["extension-module"] }
pyo3-async-runtimes = { version = "0.27.0", features = ["tokio-runtime"] }
tokio = { version = "1.48.0", features = ["rt", "rt-multi-thread", "macros"] }
chrono = "0.4.42"
reqwest = "0.12.24"
thiserror = "2.0.17"
log = "0.4.28"
bitflags = "2.10.0"

[profile.release]
opt-level = "z"
debug = false
strip = true
lto = true
codegen-units = 1
